name: main

on:
  # manual
  workflow_dispatch:
  
  # when push
  push:
    branches: [main, master]

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  pages: write      # to deploy to Pages
  contents: write
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      # Setup node: https://github.com/actions/setup-node
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: yarn install
        run: yarn install
        
      - name: yarn build
        run: yarn build
        
      # Upload docs site: https://github.com/marketplace/actions/upload-a-build-artifact
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: page-site
          path: public
            
      # Publish docs: https://github.com/JamesIves/github-pages-deploy-action
      - name: publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          force: true
          branch: gh-pages
          folder: public
          git-config-name: dosymep
          git-config-email: dosymep@gmail.com
